### ISSUE TITLE
Troubleshoot external links

### ISSUE THREAD

**Issue by sbddesign** [sbddesign/bolt12.org#28]
Why does my external link to the Offers PR in the header take an entire 2 seconds to even begin to pretend like it wants to load the page? I understand it falls outside of Next's snappy routing system, but it should at least open a blank page and pretend like it's loading. Behaves this way with next `Link` component, with vanilla `<a>`, and from dev server as well as production build.

**Comment by sbddesign** [comment]
@thebrandonlucas this is one I could use help with. While I have more experience wit hNextJS I think, I have no idea why this is the case, so your guess is as good as mine.

**Comment by thebrandonlucas** [comment]
@sbddesign I think this may just be the result of slow page loading. For instance, try to copy the [link](https://github.com/lightning/bolts/pull/798), open a new tab in your browser, and paste and go. It takes about the same time (approx 2 seconds) to load the page as it does for me to open it from clicking the "Read the Spec" link. I think this is just a network limitation from Github's server?

One thing we might be able to do to make it feel like it's loading faster is open a new tab on click with `target="_blank"`. After all, it's the only external link in the header, so I don't think the behavior would feel unnatural. If you like that, I can go ahead and do that. Lmk what you think.

**Comment by sbddesign** [comment]
Sure, new tab sounds good. Upon closer inspection, I realize the issue is Arc browser (annoyingly). Clicking the link in Brave browser provides immediate feedback at the browser level: there is a loading spinner by the title in the browser tab. However, Arc just does nothing and provides no feedback a link has been clicked.
