### ISSUE TITLE
Human Readable Address - updated text

### ISSUE THREAD

**Issue by sbddesign** [sbddesign/bolt12.org#42]
There is a BIP, BLIP, and BOLT for human readable address, apparently, so find a way to get all of that added

**Comment by sbddesign** [comment]
After further investigation, here would be the other documents to include:
- [BOLTs PR 1136](https://github.com/lightning/bolts/pull/1136)
- [bLIP 0032](https://github.com/lightning/blips/blob/master/blip-0032.md)

I kind of think we should just leave this detail off of the homepage. What do you think @moneyball? Look at these tiny little project descriptions:

![image](https://github.com/sbddesign/bolt12.org/assets/2414177/ed660f23-8206-4d59-b4c5-66acbd22271c)

I think the purpose here on the homepage is simply to show off "hey, there are some cool projects here". Furthermore, it appears to me that the bLIP and the BOLT are kind of optional components here. The bLIP and BOLT are just *if* a lightning client decides it wants to resolve the DNS record over onion messages...it could also just do it's own DNS or DNSoH lookup. Correct me if I am wrong on that, somebody.

If it's important to link to where all the discussion is happening for all this, maybe we make a dedicated page for this under the "Developer Docs" section of the site and describe overall how all this works and then link out to the BIP, BOLT, and bLIP.

**Comment by moneyball** [comment]
Yeah upon closer inspection I think you are right.

**Comment by sbddesign** [comment]
> Yeah upon closer inspection I think you are right.

Got it, I will close this issue and we can re-open later if needed
